all:
	time gcc -o0 Main.c -s -lm 2> times.txt
	time gcc -o1 Main.c  -s -lm   2> times.txt                                                                                                                                                                     
	time gcc -o3 Main.c -s -lm  2> times.txt                                                                                                                                                                   
	time gcc -ofast Main.c -s -lm 2> times.txt
	time gcc -os Main.c -s -lm  2> times.txt                                                                                                    